#!/bin/bash

######################################################################################
## Script for automatic control over VMware Workstation virtual machines
## Copyright (C) 2011 Almir Dzinovic <almir@dzinovic.net>
##
## This program is free software; you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free Software
## Foundation; either version 3 of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
## FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
##
## Get the full text of the GPL here: http://www.gnu.org/licenses/gpl.txt
######################################################################################

### BEGIN INIT INFO
# Provides: VMware VMs Control
# Required-Start: $local_fs $network $syslog
# Required-Stop:
# Default-Start: 2 3 5
# Default-Stop: 0 6
# Short-Description: Starts or stops VMware Workstation VMs
# Description: Starts or stops VMware Workstation virtual machines
### END INIT INFO

. /lib/lsb/init-functions

DESC="VMware Workstation VMs control script"
NAME="vmsctrl"

CONFFILE="/etc/default/vmsctrl.conf"
. $CONFFILE

VMACHINES=("`ls $VMSPATH`")

case "$1" in
  start)
        log_daemon_msg "Starting virtual machines"
           # Starting virtual machines
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun start $VMSPATH/$i/$i.vmx nogui"
           done
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Shutting down virtual machines"
           # Shutting down virtual machines
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun stop $VMSPATH/$i/$i.vmx soft"
           done
        log_end_msg $?
        ;;
  force-stop)
        log_daemon_msg "Powering off virtual machines"
           # Powering off virtual machines
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun stop $VMSPATH/$i/$i.vmx hard"
           done
        log_end_msg $?
        ;;
  restart)
        log_daemon_msg "Restarting virtual machines"
           # Restarting virtual machines
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun reset $VMSPATH/$i/$i.vmx soft"
           done
        log_end_msg $?
        ;;
  force-restart)
        log_daemon_msg "Power cycling virtual machines"
           # Power cycling virtual machines
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun reset $VMSPATH/$i/$i.vmx hard"
           done
        log_end_msg $?
        ;;
  suspend)
        log_daemon_msg "Suspending virtual machines (soft)"
           # Suspending virtual machines after running system scripts
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun suspend $VMSPATH/$i/$i.vmx soft"
           done
        log_end_msg $?
        ;;
  force-suspend)
        log_daemon_msg "Suspending virtual machines (hard)"
           # Suspending virtual machines without running system scripts
           for i in $VMACHINES
           do
              su - "$USERNAME" -c "vmrun suspend $VMSPATH/$i/$i.vmx hard"
           done
        log_end_msg $?
        ;;
  *)
        log_success_msg "Usage: "$0" {start|stop|force-stop|restart|force-restart|suspend|force-suspend}"
        exit 1
        ;;
esac

exit 0
