#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

CONFFILE=/etc/default/vmsctrl.conf

if [ -e "$CONFFILE" ]; then
    . $CONFFILE || true

    db_set vmsctrl/username $USERNAME
    db_set vmsctrl/vmspath $VMSPATH
fi

exit 0
