#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

CONFFILE=/etc/default/vmsctrl.conf

if [ -e "$CONFFILE" ]; then
    . $CONFFILE || true
fi

db_set vmsctrl/username $USERNAME
db_set vmsctrl/vmspath $VMSPATH

db_input high vmsctrl/username || true
db_input high vmsctrl/vmspath || true
db_go || true

exit 0

