#!/bin/sh

set -e

CONFFILE=/etc/default/vmsctrl.conf

if [ "$1" = "purge" ]; then
    rm -f "$CONFFILE"
fi

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

#DEBHELPER#

exit 0
