#!/bin/sh

set -e

case "$1" in
    install|upgrade)
        INITSCRIPT="/etc/init.d/vmsctrl"
        if [ -e "$INITSCRIPT" ]; then
            /etc/init.d/vmsctrl stop
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
