#!/bin/sh

set -e

case "$1" in
    install)
        if [ -z "$(which vmrun)" ]; then
            . /usr/share/debconf/confmodule
            db_version 2.0

            db_input critical vmsctrl/novmrun || true
            db_go || true
            db_stop

            exit 1
        fi
    ;;

    upgrade)
        INITSCRIPT="/etc/init.d/vmsctrl"
        if [ -e "$INITSCRIPT" ]; then
            invoke-rc.d vmsctrl stop
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
